<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_SimulatedIn_DG" Id="{aac0b935-999d-4985-8292-12706ec9a1c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimulatedIn_DG IMPLEMENTS ITF_Regelschuif_IN_DG

VAR
	internalState : sint;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="get" Id="{79e034de-ecf5-433b-b644-ff4e1cc32dd5}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD get : SINT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[get := internalState;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SimulatedIn_DG">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_SimulatedIn_DG.get">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>