<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_SimulatedOutOpen_DG" Id="{912669fe-b594-46ab-9d35-fdb4a26b8827}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimulatedOutOpen_DG IMPLEMENTS ITF_Regelschuif_OutOpen_DG
VAR
	internalState : BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="set" Id="{4e3c24d6-45b0-4602-8092-80b72458db64}">
      <Declaration><![CDATA[METHOD set : BOOL
VAR_INPUT
	state : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[internalState := state;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SimulatedOutOpen_DG">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_SimulatedOutOpen_DG.set">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>