<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_Uitmalen" Id="{9ae4d82e-20f8-4e09-9aaa-bd1ddcd0f3cd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Uitmalen
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Uitmalen">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>