<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_Pomp" Id="{06ecb101-bef7-4b99-b37c-3c3f30794da2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Pomp
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Pomp">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>