<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_Regelschuif_DG" Id="{197a057b-7e77-4001-97d3-497a9b935830}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Regelschuif_DG
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//test]]></ST>
    </Implementation>
    <LineIds Name="FB_Regelschuif_DG">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>