<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_Regelschuif_AFO" Id="{e3716e21-c926-4b53-b092-edc4b4bb1690}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Regelschuif_AFO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Regelschuif_AFO">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>