<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SimulatedDigIn" Id="{387a2786-04b8-428a-9692-51d1a64f4124}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimulatedDigIn IMPLEMENTS ITF_DigIn
VAR
	internalState : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="get" Id="{ab4738cb-7b7e-4807-b9e1-d626a405b4f7}">
      <Declaration><![CDATA[METHOD get : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[get := internalState;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SimulatedDigIn">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SimulatedDigIn.get">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>