<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_SimulatedDigOutOpen_AFO" Id="{344ce2d3-5a32-466b-a26c-1b17147eb765}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimulatedDigOutOpen_AFO IMPLEMENTS ITF_Schuif_DigOutOpen_AFO
VAR
	internalState : BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="set" Id="{4c281178-76bf-4d71-87b0-d914c8aff672}">
      <Declaration><![CDATA[METHOD set : BOOL
VAR_INPUT
	state : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[internalState := state;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SimulatedDigOutOpen_AFO">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_SimulatedDigOutOpen_AFO.set">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>