<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_SimulatedOutOpen_DG" Id="{dd7eec1a-cd3e-4e90-b599-3cbc509f8f0e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimulatedOutOpen_DG IMPLEMENTS ITF_Regelschuif_OutOpen_DG
VAR
	internalState : BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="set" Id="{832fdc31-444b-4857-8ebe-29836373b23b}">
      <Declaration><![CDATA[METHOD set : BOOL
VAR_INPUT
	state : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[internalState := state;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SimulatedOutOpen_DG">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_SimulatedOutOpen_DG.set">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>