<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_SimulatedIn_DG" Id="{63c47254-f5df-4fce-ac77-dfc31f6df536}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimulatedIn_DG IMPLEMENTS ITF_Regelschuif_IN_DG

VAR
	internalState : sint;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="get" Id="{6aed3395-d16f-4f02-8d40-c7ce69b68c06}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD get : SINT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[get := internalState;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SimulatedIn_DG">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_SimulatedIn_DG.get">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>