<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="FB_SimulatedDigOut" Id="{e7465166-7df2-484b-8c65-5063e075f75b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimulatedDigOut IMPLEMENTS ITF_DigOut
VAR
	internalState : BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="set" Id="{007f49f7-25b6-41f1-8953-09f7abb4f181}">
      <Declaration><![CDATA[METHOD set : BOOL
VAR_INPUT
	state : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[internalState := state;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_SimulatedDigOut">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_SimulatedDigOut.set">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>